<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LlibresDeTextSeeder extends Seeder
{
    public function run()
    {
        DB::table('llibres_de_text')->insert([
            [
                'curs' => '2n ESO',
                'titol' => 'Matemàtiques',
                'editorial' => 'Anaya',
                'observacions' => 'Inclou exercicis addicionals al final de cada capítol',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '5è Primària',
                'titol' => 'Història universal',
                'editorial' => 'Vicens Vives',
                'observacions' => 'Amb capítols actualitzats sobre el segle XXI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '1r ESO',
                'titol' => 'Història i geografia',
                'editorial' => 'Vicens Vives',
                'observacions' => 'Llibre actualitzat a la nova edició 2023',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '4t Primària',
                'titol' => 'Història de Catalunya',
                'editorial' => 'Vicens Vives',
                'observacions' => 'Mapes històrics i línies temporals',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '6è Primària',
                'titol' => 'Ciències socials',
                'editorial' => 'Vicens Vives',
                'observacions' => 'Projectes en grup amb enfocament pràctic',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '2n Batxillerat',
                'titol' => 'Economia de l\'empresa',
                'editorial' => 'SM',
                'observacions' => 'Enfocament pràctic amb exemples reals d\'empreses',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '3r ESO',
                'titol' => 'Biologia i Geologia',
                'editorial' => 'Santillana',
                'observacions' => 'Nou llibre digital disponible',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '1r Primària',
                'titol' => 'Matemàtiques bàsiques',
                'editorial' => 'Anaya',
                'observacions' => 'Activitats manipulatives i joc interactiu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '2n Primària',
                'titol' => 'Llengua castellana',
                'editorial' => 'SM',
                'observacions' => 'Lectures obligatòries amb activitats',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '4t ESO',
                'titol' => 'Física i Química',
                'editorial' => 'Ed. Teide',
                'observacions' => 'Versió revisada per a l\'any 2024',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '1r Batxillerat',
                'titol' => 'Física',
                'editorial' => 'McGraw-Hill',
                'observacions' => 'Inclou exercicis pràctics i problemes de física moderna',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '6è Primària',
                'titol' => 'Anglès',
                'editorial' => 'Oxford',
                'observacions' => 'Inclou exercicis pràctics de conversa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '1r ESO',
                'titol' => 'Llengua catalana i literatura',
                'editorial' => 'Edicions 62',
                'observacions' => 'Conté activitats de comprensió lectora i gramàtica',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '2n Batxillerat',
                'titol' => 'Matemàtiques II',
                'editorial' => 'Santillana',
                'observacions' => 'Amb exercicis avançats de càlcul diferencial',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '3r ESO',
                'titol' => 'Tecnologia',
                'editorial' => 'SM',
                'observacions' => 'Contingut amb enfocament pràctic per a projectes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '2n ESO',
                'titol' => 'Física i Química',
                'editorial' => 'Oxford University Press',
                'observacions' => 'Actualització 2024 amb experiments pràctics',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '5è Primària',
                'titol' => 'Ciències de la naturalesa',
                'editorial' => 'Anaya',
                'observacions' => 'Inclou experiments pràctics',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '1r ESO',
                'titol' => 'Ciències socials',
                'editorial' => 'Vicens Vives',
                'observacions' => 'Inclou mapes actualitzats de Catalunya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '3r Primària',
                'titol' => 'Llengua catalana',
                'editorial' => 'Santillana',
                'observacions' => 'Lectures i activitats de gramàtica',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '4t ESO',
                'titol' => 'Llengua Castellana i Literatura',
                'editorial' => 'Santillana',
                'observacions' => 'Inclou lectures obligatòries del curs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '2n ESO',
                'titol' => 'Història',
                'editorial' => 'Vicens Vives',
                'observacions' => 'Edició 2023 amb actualitzacions històriques',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '3r Primària',
                'titol' => 'Ciències socials',
                'editorial' => 'Vicens Vives',
                'observacions' => 'Inclou mapes i activitats d\'exploració',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '4t ESO',
                'titol' => 'Història de l\'Art',
                'editorial' => 'Edicions Vicens Vives',
                'observacions' => 'Inclou contingut visual en línia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '1r ESO',
                'titol' => 'Música',
                'editorial' => 'Edicions 62',
                'observacions' => 'Inclou exercicis de teoria musical i audicions',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '2n Primària',
                'titol' => 'Ciències naturals',
                'editorial' => 'Santillana',
                'observacions' => 'Inclou experiments senzills per fer a casa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '4t Primària',
                'titol' => 'Matemàtiques',
                'editorial' => 'SM',
                'observacions' => 'Fraccions i geometria',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '2n Primària',
                'titol' => 'Llengua catalana',
                'editorial' => 'Vicens Vives',
                'observacions' => 'Activitats de comprensió lectora',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '6è Primària',
                'titol' => 'Matemàtiques',
                'editorial' => 'Anaya',
                'observacions' => 'Àlgebra i estadística bàsica',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '1r Primària',
                'titol' => 'Coneixement del medi',
                'editorial' => 'Santillana',
                'observacions' => 'Activitats a l\'aire lliure',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '1r Batxillerat',
                'titol' => 'Història del món contemporani',
                'editorial' => 'Vicens Vives',
                'observacions' => 'Inclou anàlisis de casos històrics',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '6è Primària',
                'titol' => 'Ciències socials',
                'editorial' => 'Vicens Vives',
                'observacions' => 'Projectes en grup amb enfocament pràctic',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '1r Primària',
                'titol' => 'Coneixement del medi',
                'editorial' => 'Santillana',
                'observacions' => 'Amb activitats pràctiques i interactives',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '2n Primària',
                'titol' => 'Matemàtiques',
                'editorial' => 'Anaya',
                'observacions' => 'Inclou jocs matemàtics per a reforç',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '3r Primària',
                'titol' => 'Llengua catalana',
                'editorial' => 'Edicions 62',
                'observacions' => 'Llibre amb exercicis de lectura comprensiva',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '4t Primària',
                'titol' => 'Història de Catalunya',
                'editorial' => 'Vicens Vives',
                'observacions' => 'Inclou línies de temps i mapes interactius',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '5è Primària',
                'titol' => 'Educació artística',
                'editorial' => 'McGraw-Hill',
                'observacions' => 'Activitats creatives i manualitats',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '6è Primària',
                'titol' => 'Geografia',
                'editorial' => 'Santillana',
                'observacions' => 'Amb mapes i projectes de recerca',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '1r Batxillerat',
                'titol' => 'Història de l\'art',
                'editorial' => 'Vicens Vives',
                'observacions' => 'Inclou imatges d\'obres mestres del renaixement',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '2n Batxillerat',
                'titol' => 'Filosofia',
                'editorial' => 'Edicions 62',
                'observacions' => 'Amb textos filosòfics clàssics i contemporanis',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '1r Batxillerat',
                'titol' => 'Matemàtiques I',
                'editorial' => 'Santillana',
                'observacions' => 'Amb exercicis avançats de geometria i àlgebra',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '6è Primària',
                'titol' => 'Història moderna',
                'editorial' => 'Oxford',
                'observacions' => 'Inclou projectes d\'investigació històrica',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '5è Primària',
                'titol' => 'Llengua castellana',
                'editorial' => 'SM',
                'observacions' => 'Exercicis de redacció i ortografia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '2n Batxillerat',
                'titol' => 'Llengua catalana i literatura',
                'editorial' => 'Anaya',
                'observacions' => 'Inclou anàlisi de textos literaris catalans',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '1r Primària',
                'titol' => 'Educació física',
                'editorial' => 'SM',
                'observacions' => 'Activitats per desenvolupar habilitats motrius',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '4t Primària',
                'titol' => 'Medi natural',
                'editorial' => 'Anaya',
                'observacions' => 'Experiments de ciències i projectes de medi ambient',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '6è Primària',
                'titol' => 'Ciències naturals',
                'editorial' => 'McGraw-Hill',
                'observacions' => 'Inclou activitats d\'experimentació',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '5è Primària',
                'titol' => 'Matemàtiques',
                'editorial' => 'Ed. Teide',
                'observacions' => 'Inclou problemes matemàtics aplicats',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '3r Primària',
                'titol' => 'Educació artística',
                'editorial' => 'Edicions 62',
                'observacions' => 'Activitats creatives amb materials reciclats',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '1r Primària',
                'titol' => 'Música',
                'editorial' => 'Santillana',
                'observacions' => 'Inclou activitats amb instruments bàsics',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'curs' => '4t Primària',
                'titol' => 'Matemàtiques avançades',
                'editorial' => 'Anaya',
                'observacions' => 'Amb jocs i activitats interactives',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
        ]);
    }
}
