<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\LlibreDeText;
use App\Models\Category;
use App\Models\User;

class LlibreDeTextSeeder extends Seeder
{
    public function run()
    {
        $categories = Category::all();
        $users = User::all();

        LlibreDeText::insert([
            [
                    'titol' => 'Matemàtiques bàsiques',
                    'curs' => '1r Primària',
                    'editorial' => 'Anaya',
                    'observacions' => 'Activitats manipulatives i joc interactiu',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Història del món contemporani',
                    'curs' => '1r Batxillerat',
                    'editorial' => 'Vicens Vives',
                    'observacions' => 'Inclou anàlisis de casos històrics',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Llengua catalana i literatura',
                    'curs' => '2n ESO',
                    'editorial' => 'Edicions 62',
                    'observacions' => 'Amb activitats de comprensió lectora',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Ciències socials',
                    'curs' => '3r Primària',
                    'editorial' => 'Santillana',
                    'observacions' => 'Amb activitats pràctiques sobre medi ambient',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Tecnologia',
                    'curs' => '4t ESO',
                    'editorial' => 'SM',
                    'observacions' => 'Projectes interactius de robòtica',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Física i Química',
                    'curs' => '1r Batxillerat',
                    'editorial' => 'McGraw-Hill',
                    'observacions' => 'Problemes avançats i experiments de laboratori',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Anglès',
                    'curs' => '5è Primària',
                    'editorial' => 'Oxford',
                    'observacions' => 'Inclou àudios per a millorar la pronunciació',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Història de l\'Art',
                    'curs' => '2n Batxillerat',
                    'editorial' => 'Vicens Vives',
                    'observacions' => 'Amb il·lustracions i anàlisis d\'obres mestres',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Biologia',
                    'curs' => '3r ESO',
                    'editorial' => 'Santillana',
                    'observacions' => 'Inclou experiments de laboratori virtual',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Geografia',
                    'curs' => '4t Primària',
                    'editorial' => 'SM',
                    'observacions' => 'Projectes de recerca sobre paisatges de Catalunya',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Història Universal',
                    'curs' => '5è Primària',
                    'editorial' => 'Vicens Vives',
                    'observacions' => 'Capítols dedicats a les civilitzacions antigues',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Educació física',
                    'curs' => '1r Primària',
                    'editorial' => 'SM',
                    'observacions' => 'Activitats motrius i jocs a l\'aire lliure',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Ciències Naturals',
                    'curs' => '2n Primària',
                    'editorial' => 'Santillana',
                    'observacions' => 'Experiments senzills per fer a casa',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Química avançada',
                    'curs' => '2n Batxillerat',
                    'editorial' => 'McGraw-Hill',
                    'observacions' => 'Exercicis pràctics d\'anàlisi química',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Matemàtiques avançades',
                    'curs' => '4t Primària',
                    'editorial' => 'Edicions Teide',
                    'observacions' => 'Amb jocs interactius per a millorar les habilitats',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Literatura castellana',
                    'curs' => '4t ESO',
                    'editorial' => 'Santillana',
                    'observacions' => 'Inclou obres de referència de la literatura espanyola',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Història i Geografia',
                    'curs' => '2n ESO',
                    'editorial' => 'Vicens Vives',
                    'observacions' => 'Amb activitats per a millorar la comprensió espacial',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Filosofia',
                    'curs' => '1r Batxillerat',
                    'editorial' => 'Edicions 62',
                    'observacions' => 'Textos filosòfics clàssics amb activitats de debat',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Ciències de la Terra',
                    'curs' => '3r ESO',
                    'editorial' => 'Santillana',
                    'observacions' => 'Amb projectes de recerca ambiental',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Educació Visual i Plàstica',
                    'curs' => '3r Primària',
                    'editorial' => 'SM',
                    'observacions' => 'Activitats creatives amb tècniques mixtes',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Història Universal',
                    'curs' => '5è Primària',
                    'editorial' => 'Vicens Vives',
                    'observacions' => 'Capítols dedicats a les civilitzacions antigues',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Educació física',
                    'curs' => '1r Primària',
                    'editorial' => 'SM',
                    'observacions' => 'Activitats motrius i jocs a l\'aire lliure',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Ciències Naturals',
                    'curs' => '2n Primària',
                    'editorial' => 'Santillana',
                    'observacions' => 'Experiments senzills per fer a casa',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Química avançada',
                    'curs' => '2n Batxillerat',
                    'editorial' => 'McGraw-Hill',
                    'observacions' => 'Exercicis pràctics d\'anàlisi química',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Matemàtiques avançades',
                    'curs' => '4t Primària',
                    'editorial' => 'Edicions Teide',
                    'observacions' => 'Amb jocs interactius per a millorar les habilitats',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Literatura castellana',
                    'curs' => '4t ESO',
                    'editorial' => 'Santillana',
                    'observacions' => 'Inclou obres de referència de la literatura espanyola',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Història i Geografia',
                    'curs' => '2n ESO',
                    'editorial' => 'Vicens Vives',
                    'observacions' => 'Amb activitats per a millorar la comprensió espacial',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Filosofia',
                    'curs' => '1r Batxillerat',
                    'editorial' => 'Edicions 62',
                    'observacions' => 'Textos filosòfics clàssics amb activitats de debat',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Ciències de la Terra',
                    'curs' => '3r ESO',
                    'editorial' => 'Santillana',
                    'observacions' => 'Amb projectes de recerca ambiental',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Educació Visual i Plàstica',
                    'curs' => '3r Primària',
                    'editorial' => 'SM',
                    'observacions' => 'Activitats creatives amb tècniques mixtes',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Història de Catalunya',
                    'curs' => '4t Primària',
                    'editorial' => 'Vicens Vives',
                    'observacions' => 'Inclou mapes històrics',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Matemàtiques bàsiques',
                    'curs' => '2n Primària',
                    'editorial' => 'Anaya',
                    'observacions' => 'Amb exercicis pràctics',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Història de l\'Art',
                    'curs' => '2n ESO',
                    'editorial' => 'SM',
                    'observacions' => 'Il·lustracions d\'obres clàssiques',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Anglès intermedi',
                    'curs' => '3r ESO',
                    'editorial' => 'Oxford',
                    'observacions' => 'Inclou àudios per millorar la comprensió oral',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Biologia i Geologia',
                    'curs' => '4t ESO',
                    'editorial' => 'Santillana',
                    'observacions' => 'Amb exercicis d\'experimentació',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Educació per la ciutadania',
                    'curs' => '1r ESO',
                    'editorial' => 'Vicens Vives',
                    'observacions' => 'Llibre amb exercicis de reflexió personal',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Física',
                    'curs' => '2n Batxillerat',
                    'editorial' => 'McGraw-Hill',
                    'observacions' => 'Amb problemes de física avançada',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Llengua castellana',
                    'curs' => '5è Primària',
                    'editorial' => 'Santillana',
                    'observacions' => 'Exercicis d\'ortografia i gramàtica',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Química bàsica',
                    'curs' => '3r ESO',
                    'editorial' => 'SM',
                    'observacions' => 'Amb experiments de laboratori',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Música',
                    'curs' => '1r Primària',
                    'editorial' => 'Santillana',
                    'observacions' => 'Amb cançons populars',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Història moderna',
                    'curs' => '4t ESO',
                    'editorial' => 'Vicens Vives',
                    'observacions' => 'Amb material audiovisual en línia',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Llengua anglesa',
                    'curs' => '1r ESO',
                    'editorial' => 'Oxford',
                    'observacions' => 'Inclou exercicis de comprensió lectora',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Matemàtiques aplicades',
                    'curs' => '2n Primària',
                    'editorial' => 'Anaya',
                    'observacions' => 'Amb jocs interactius per reforçar conceptes',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Història del segle XX',
                    'curs' => '1r Batxillerat',
                    'editorial' => 'Vicens Vives',
                    'observacions' => 'Inclou documentals complementaris',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Ciències Naturals',
                    'curs' => '4t Primària',
                    'editorial' => 'SM',
                    'observacions' => 'Amb experiments senzills',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Matemàtiques II',
                    'curs' => '2n Batxillerat',
                    'editorial' => 'Anaya',
                    'observacions' => 'Exercicis avançats d\'àlgebra i càlcul',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Història de Roma',
                    'curs' => '4t ESO',
                    'editorial' => 'Vicens Vives',
                    'observacions' => 'Inclou mapes històrics i reconstruccions 3D',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Educació ètica',
                    'curs' => '3r ESO',
                    'editorial' => 'SM',
                    'observacions' => 'Reflexions sobre valors i responsabilitat social',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Geografia física',
                    'curs' => '1r Batxillerat',
                    'editorial' => 'Santillana',
                    'observacions' => 'Amb activitats de camp per explorar terrenys',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Economia bàsica',
                    'curs' => '2n ESO',
                    'editorial' => 'Edicions 62',
                    'observacions' => 'Conceptes bàsics d\'economia amb exercicis',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Física teòrica',
                    'curs' => '2n Batxillerat',
                    'editorial' => 'McGraw-Hill',
                    'observacions' => 'Problemes de física avançada',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Llengua i literatura catalanes',
                    'curs' => '5è Primària',
                    'editorial' => 'Edicions 62',
                    'observacions' => 'Amb activitats de redacció i comprensió lectora',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Educació en valors',
                    'curs' => '1r Primària',
                    'editorial' => 'Santillana',
                    'observacions' => 'Exercicis per treballar la convivència i la solidaritat',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'titol' => 'Història del segle XXI',
                    'curs' => '2n ESO',
                    'editorial' => 'Vicens Vives',
                    'observacions' => 'Amb anàlisis d\'esdeveniments recents',
                    'user_id' => $users->random()->id,
                    'category_id' => $categories->where('name', 'Llibres de text')->first()->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
    
            
            
        ]);
    }
}
